package com.ithirteeng.secondpatternsclientproject.common.uikit

import androidx.compose.ui.graphics.Color

val themeLightPrimary = Color(0xFF6750A4)
val themeLightOnPrimary = Color(0xFFffffff)
val themeLightPrimaryContainer = Color(0xFFEADDFF)
val themeLightOnPrimaryContainer = Color(0xFF21005D)
val themeLightSecondary = Color(0xFF625B71)
val themeLightOnSecondary = Color(0xFFffffff)
val themeLightSecondaryContainer = Color(0xFFE8DEF8)
val themeLightOnSecondaryContainer = Color(0xFF1D192B)
val themeLightTertiary = Color(0xFF1160a4)
val themeLightOnTertiary = Color(0xFFffffff)
val themeLightTertiaryContainer = Color(0xFFd2e4ff)
val themeLightOnTertiaryContainer = Color(0xFF001c39)
val themeLightError = Color(0xFFB3261E)
val themeLightErrorContainer = Color(0xFFF9DEDC)
val themeLightOnError = Color(0xFFFFFFFF)
val themeLightOnErrorContainer = Color(0xFF410E0B)
val themeLightBackground = Color(0xFFFFFFFF)
val themeLightOnBackground = Color(0xFF1C1B1F)
val themeLightSurface = Color(0xFFFFFBFE)
val themeLightOnSurface = Color(0xFF1C1B1F)
val themeLightSurfaceVariant = Color(0xFFF7F2FA)
val themeLightOnSurfaceVariant = Color(0xFF49454F)
val themeLightOutline = Color(0xFF79747E)
val themeLightInverseOnSurface = Color(0xFFF4EFF4)
val themeLightInverseSurface = Color(0xFF313033)
val themeLightInversePrimary = Color(0xFFadc6ff)

val themeDarkPrimary = Color(0xFFD0BCFF)
val themeDarkOnPrimary = Color(0xFF381E72)
val themeDarkPrimaryContainer = Color(0xFF4F378B)
val themeDarkOnPrimaryContainer = Color(0xFFEADDFF)
val themeDarkSecondary = Color(0xFFCCC2DC)
val themeDarkOnSecondary = Color(0xFFE8DEF8)
val themeDarkSecondaryContainer = Color(0xFF4A4458)
val themeDarkOnSecondaryContainer = Color(0xFFE8DEF8)
val themeDarkTertiary = Color(0xFF9fc9ff)
val themeDarkOnTertiary = Color(0xFF00315c)
val themeDarkTertiaryContainer = Color(0xFF004882)
val themeDarkOnTertiaryContainer = Color(0xFFd2e4ff)
val themeDarkError = Color(0xFFF2B8B5)
val themeDarkErrorContainer = Color(0xFF8C1D18)
val themeDarkOnError = Color(0xFF601410)
val themeDarkOnErrorContainer = Color(0xFFF9DEDC)
val themeDarkBackground = Color(0xFF1C1B1F)
val themeDarkOnBackground = Color(0xFFE6E1E5)
val themeDarkSurface = Color(0xFF1C1B1F)
val themeDarkOnSurface = Color(0xFFE6E1E5)
val themeDarkSurfaceVariant = Color(0xFF1D1B20)
val themeDarkOnSurfaceVariant = Color(0xFFCAC4D0)
val themeDarkOutline = Color(0xFF938F99)
val themeDarkInverseOnSurface = Color(0xFF1C1B1F)
val themeDarkInverseSurface = Color(0xFFE6E1E5)
val themeDarkInversePrimary = Color(0xFF355ca8)

val activeAccountColor = Color(0xFF6AA341)
val closedAccountColor = Color(0xFFA34141)
val frozenAccountColor = Color(0xFF25D5B7)